title: MCMICRO Hackathon
nav_title: First MCMICRO Micro hackathon 2022<br><small>In person in Heidelberg and online.</small>

event_date: 20-21 October 2022

author: Florian Wuennemann
mailbox_address: flowuenne@gmail.com

description:
  The SchapiroLab in Heidelberg is organizing its first MCMICRO hackathon.


url: "https://schapirolabor.github.io/mcmicro_hackathon_2022/"
github_repo: schapirolabor.github.io

theme: minima

# The actual visibility of the nav bar links is influenced by the event_status
# and registration_status flags below
header_pages:
  - agenda.md
  - about.md
  - projects.md
  - instructions.md
  #- videos-slides.md
  - resources.md


# Event status
#   soon = event is yet to happen
#    now = event is currently happening
#   over = event has happened
#  (demo = show all pages to demonstrate the template)
event_status: soon

# Open and close the registration form
#   soon = Registration has not yet opened
#   open = Registration form is open
# closed = Registration form is now closed
#  (demo = show all pages to demonstrate the template)
registration_status: closed

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/mcmicro-logo.png
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"